import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";

import {
  getFirestore,
  collection,
  doc,
  getDoc,
  setDoc,
  updateDoc,
} from "firebase/firestore";

import _ from "lodash";

const emails = [
  "kunapak11@hotmail.com",
  "chawewan@thaimice.com",
  "pantita.nukulkit@gmail.com",
  "suchinah@hotmail.com",
  "Supachoke.b@gmail.com",
  "kntv@novonordisk.com",
  "isreenew@hotmail.com",
  "panuddass@gmail.com",
  "Churuangsuk@gmail.com",
  "Joyprom@hotmail.com",
  "nitchakarn.lai@gmail.com",
  "ake.xda@gmail.com",
  "pimnapat.are@gmail.com",
  "5614077bm21@gmail.com",
  "zippy_keaw@hotmail.com",
  "bird_poempoon@hotmail.com",
  "luktan9@hotmail.com",
  "marentrd@gmail.com",
  "maitantivit@hotmail.com",
  "yuibeauty74@hotmail.com",
  "sirbj1@gmail.com",
  "panyakorn27@hotmail.com",
  "Maimelovely@hotmail.com",
  "meng_gy@hotmail.com",
  "Pimpakan102@gmail.com",
  "j.kittrakulrat@gmail.com",
  "nat_dvm_md@hotmail.com",
  "pirapatsinchai@gmail.com",
  "panuwat.tan@mahidol.ac.th",
  "supapong.med23@gmail.com",
  "seia.bhn@gmail.com",
  "nicha_tangkwa@hotmail.com",
  "pongsakorn.kit@hotmail.com",
  "sunny_ngae@hotmail.com",
  "preeyapat.chattieng@gmail.com",
  "ice_tpg@hotmail.com",
  "david.leung.endo@gmail.com",
  "drmedchartwut2210@gmail.com",
  "naamneanny@hotmail.com",
  "kaematha@gmail.com",
  "jirasakuldech@yahoo.com",
  "huiendocrine@gmail.com",
  "eung0804@gmail.com",
  "chinokii.wii@gmail.com",
  "nichanun2@gmail.com",
  "dr_cardiomed@yahoo.com",
  "niboon.tha@gmail.com",
  "taitai_2548@hotmail.com",
  "napaporn.pe@western.ac.th",
  "apinoppensiricu@gmail.com",
  "jirawat_p@kkumail.com",
  "narawadee_si@windowslive.com",
  "tonlers_rbjcs2@hotmail.com",
  "nahmfonpirun@gmail.com",
  "jeabkaoil2559@gmail.com",
  "chatkarin_ball@hotmail.com",
  "myoo_216@hotmail.com",
  "peemthanawarath@gmail.com",
  "natthinee0485@gmail.com",
  "Sathienrapong@hotmail.com",
  "akp.zenith@gmail.com",
  "sponge_aon@hotmail.com",
  "Ythapimai@gmail.com",
  "natta_sal@hotmail.com",
  "chatchai.orsuwana@gmail.com",
  "Dutsadee.char@gmail.com",
  "roseolarrosea@hotmail.com",
  "david.leung.endo@gmail.com",
  "thanat.si080@gmail.com",
  "khuanthip11@gmail.com",
  "Kingpai_universe@hotmail.com",
  "samitti.ch@gmail.com",
  "wns_sk116@hotmail.com",
  "B_pom@yahoo.com",
  "preeyapat.chattieng@gmail.com",
  "wns_sk116@hotmail.com",
  "Kanokporn.wonganankit@gmail.com",
  "bomb.chinj@gmail.com",
  "nisarat@bnc.ac.th",
  "Chaiyut025@gmail.com",
  "kamolk@yahoo.com",
  "Varasaya_a@hotmail.com",
  "Tasneem.a@cpird.in.th",
  "Por.kritsada35@gmail.com",
  "api.che@hotmail.com",
  "orawinra38@gmail.com",
  "kdineashkumar@gmail.com",
  "kdineashkumar@gmail.com",
  "Ratha.paa@gmail.com",
  "pplliieeww@gmail.com",
  "adisa.aswpts@gmail.com",
  "Vimonr123@gmail.com",
  "a_sweetcoffee@hotmail.com",
  "Chullapant.k@gmail.com",
  "Sivayos.deetes@gmail.com",
  "jibbymickey23@gmail.com",
  "tosukhowong1970@yahoo.com",
  "Fcapick072@gmail.com",
  "panchamamae@gmail.com",
  "Pollypockett@hotmail.com",
  "patcharin_nuthum@hotmail.com",
  "Pakorn31872yo@gmail.com",
  "Sirakarn.pmk@hotmail.com",
  "tuktaterm@gmail.com",
  "merry.kh8894@gmail.com",
  "phantakarn.sutaphan@gmail.com",
  "kanchaphiboon@gmail.com",
  "kanchaphiboon@gmail.com",
  "Warasinee.h@gmail.com",
  "Sorawee_pon@hotmail.com",
  "makkee42@hotmail.com",
  "surarit747@gmail.com",
  "somnuekvee@gmail.com",
  "d_tannapat@hotmail.com",
  "chetkc@gmail.com",
  "zaizai_weiwei@yahoo.com",
  "Bally@hotmail.com",
  "tpru@nordisk.com",
  "rganista@hotmail.com",
  "Ck.kisukpan@gmail.com",
  "isreenew@hotmail.com",
  "ananya.moolsil.2021@gmail.com",
  "Jallbay0lvu@gmail.com",
  "kanittha.kian@gmail.com",
  "Sprapimporn@gmail.com",
  "ananya.moolsil.2021@gmail.com",
  "Apussaneeb@gmail.com",
  "Prang6782@gmail.com",
  "dr_nakarin@hotmail.com",
  "Rtpr@novonordisk.com",
  "Pirongkuls@gmail.com",
  "Samiyo_may@hotmail.com",
  "Bass031@hotmail.com",
  "M.nareerat@hotmail.com",
  "thongsai.supat@gmail.com",
  "Spi-pnp@hotmail.com",
  "Chullapant.k@gmail.com",
  "Plaangie74@gmail.com",
  "naparat.su@mail.wu.ac.th",
  "kanokpol.seejui@gmail.com",
  "Chanudom.jane@gmail.com",
  "potjanamon_june@hotmail.com",
  "S_onions@hotmail.com",
  "tpru@novonordisk.com",
  "may.prapa1990@gmail.com",
  "we_natthaya@hotmail.com",
  "Spi-pnp@hotmail.com",
  "Prang6782@gmail.com",
  "umpn@novonordisk.com",
  "ice_tpg@hotmail.com",
  "danilwongsa9@gmail.com",
  "madamesuitcase@gmail.com",
  "pwploylada@gmail.com",
  "audy23@hotmail.com",
  "yo_yow_23@hotmail.com",
  "cc.yolsiriwat@gmail.com",
  "Watra_dg@hotmail.com",
  "Petchngam.chai@gmail.com",
  "gracezwong289@gmail.com",
  "pataninmd@hotmail.com",
  "Somvongvongterapak@hotmail.com",
  "wannyarmy40@gmail.com",
  "songporn_kai@hotmail.com",
  "Dr.kew@hotmail.com",
  "supapong.med23@gmail.com",
  "tonthiti@yahoo.com",
  "Somse2536@gmail.com",
  "Ytea@novonordisk.com",
  "phornuma11@gmail.com",
  "wannida.pi@hotmail.com",
  "suntouch.08302@gmail.com",
  "mashmany@gmail.com",
  "Pakorn31872yo@gmail.com",
  "Jubpruk@gmail.com",
  "Suthee067@gmail.com",
  "luktan9@hotmail.com",
  "montita.siri@gmail.com",
  "kitsadak@hotmail.com",
  "Si120.nun@gmail.com",
  "Ornwimol.mok@mahidol.edu",
  "athip2002@hotmail.com",
  "ueangsawat.t@gmail.com",
  "w.nutthawat@gmail.com",
  "Por.kritsada35@gmail.com",
  "Ytea@novonordisk.com",
  "phornuma11@gmail.com",
  "Chullapant.k@gmail.com",
  "pai.kankanit@gmail.com",
  "may.med29@gmail.com",
  "holy_alchemist@hotmail.com",
  "kaematha@gmail.com",
  "pthiptaveechan@gmail.com",
  "sjongsirikul@gmail.com",
  "holy_alchemist@hotmail.com",
  "wns_sk116@hotmail.com",
  "Chutinit.b@gmail.com",
  "apinoppensiricu@gmail.com",
  "a.suchavadee@gmail.com",
  "Ra_tree18@hotmail.com",
  "y.nutnicha@gmail.com",
  "Phaopongpaiboon@hotmail.com",
  "Pornrumpa.peng@gmail.com",
  "Phaopongpaiboon@hotmail.com",
  "sarutkontha@gmail.com",
  "Attasit419r@gmail.com",
  "wasuwee@thaimice.com",
  "atit@thaimice.com",
];

export const register = createAsyncThunk<void, string>(
  "ondemand/register",
  async (request, thunkApi) => {
    let db = getFirestore();
    let ref = doc(db, "video-on-demand", request);
    let docData = await getDoc(ref);
    let data: any = docData.data();
    let grant_users: string[] = data.grant_users;

    console.log(data);

    grant_users = _.union(grant_users, emails);

    await updateDoc(ref, { grant_users });
  }
);

export const ondemandSlice = createSlice({
  name: "ondemand",
  initialState: {},
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  extraReducers: (builder) => {},
});

export const {} = ondemandSlice.actions;

export default ondemandSlice.reducer;
